[package]
name = "mirage"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.3"
num-complex = "0.4.2"
anyhow = "1.0.68"
#once_cell = "*"
clap = { version = "4.0.32", features = ["derive"] }
